### PR TITLE
Guest access request UI: Extend handling of possible expiration date values

### LINKED ISSUE #3202: Guest access requests: setting expiration date to "" breaks request
Package version (if known): 13.0.3

## Describe the bug
In the guest access request timeline, the record owner can select a 

## Steps to Reproduce
1. Create a guest access request
2. Open the request timeline as record owner
3. Clear the value of the expiration date
4. Click "save"
5. Now the request has `payload.secret_link_expiration: "NaN"` and the request is broken

## Expected behavior

The payload gets set to a valid value and the request isn't broken

## Screenshots (if applicable)

Image

---

Image

### PR DESCRIPTION
**Pull request by max-moser**
Closes #3202 

Some context for the reasoning is in the commit messages

### CODE REVIEW

File: invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineRead.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ export class AccessRequestTimelineRead extends Component {
     } = this.props;
 
     const expirationDate =
-      secretLinkExpiration === 0
+      parseInt(secretLinkExpiration) === 0
```
Comment (max-moser) [inline invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineRead.js:23]: this is backwards compatible since `parseInt(0) == parseInt("0")`

File: invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineEdit.js [hunk 2]
```diff
@@ -76,17 +76,17 @@ export class AccessRequestTimelineEdit extends Component {
   initFormValues = () => {
     const {
       request: {
-        payload: { secret_link_expiration },
+        payload: { secret_link_expiration: secretLinkExpiration },
       },
     } = this.props;
 
-    if (parseInt(secret_link_expiration) === 0) {
+    if (parseInt(secretLinkExpiration) === 0 || secretLinkExpiration === "NaN") {
```
Comment (Samk13) [inline invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineEdit.js:83]:
```suggestion
    if (isNaN(parseInt(secretLinkExpiration)) || parseInt(secretLinkExpiration) === 0) {
```
String comparison to `"NaN"` is incorrect since `parseInt("NaN")` returns `NaN`, not the string `"NaN"` no?

Comment (max-moser) [reply invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineEdit.js:83]: the field has the actual string `"NaN"` stored, as visible in the screenshots: https://github.com/inveniosoftware/invenio-app-rdm/issues/3202
checking `parseInt(...) == NaN` might catch other string values as well that mark special values, not sure here

Comment (Samk13) [reply invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineEdit.js:83]: Oh, if "NaN" is coming through as a literal string, that’s a backend/serialization bug and should be fixed upstream instead. 
I'm just marking this as resolved.

Comment (max-moser) [reply invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/requests/timeline/AccessRequestTimelineEdit.js:83]: agreed, then we can kick this bad boy out again after
